### ISSUE TITLE
Question about perf considerations in `tick()`

### ISSUE THREAD

**Issue by sconover** [martinohanlon/CanaryRaspberryJuice#11]
Hi, 

I was just reading through the code and noticed the `tick()` method:

https://github.com/martinohanlon/CanaryRaspberryJuice/blob/master/src/com/stuffaboutcode/canaryraspberryjuice/RemoteSession.java#L109

```java
	/** called from the server main thread */
	public void tick() {
		
		if (origin == null) this.origin = plugin.getSpawnLocation();
		int processedCount = 0;
		String message;
		while ((message = inQueue.poll()) != null) {
			handleLine(message);
			processedCount++;
			if (processedCount >= maxCommandsPerTick) {
				plugin.getLogman().warn("Over " + maxCommandsPerTick +
					" commands were queued - deferring " + inQueue.size() + " to next tick");
				break;
			}
		}

		if (!running && inQueue.size() <= 0) {
			pendingRemoval = true;
		}
	}
```

Would you mind explaining some of the findings that led to this implementation? In particular, what are your observations about the behavior of the server at various `maxCommandsPerTick` thresholds?

Regards,
Steve

**Comment by martinohanlon** [comment]
Hi Steve,

A lot of the implementation decisions where made when the original bukkit version of RaspberryJuice was created, but I give you my insight.

The tick method is called for each session each time the minecraft server 'ticks' see CanaryRaspberryJuiceListener.onTick(). This allows the server to 'choose' when commands are processed, the upshot being that if the server is busy and not ticking, raspberry juice doesnt take up additional resources.

The maxCommandsPerTick is a threshold which stops Raspberry Juice slowing the server tick, by limiting the number of commands it will process per tick. The value of 9000 was picked through a bit of trial an error as being enough but not too many!  One of the changes I need to make at some point is make this value configurable.

I hope that helps.

Mart
