### ISSUE TITLE
No events recieved

### ISSUE THREAD

**Issue by craigem** [martinohanlon/CanaryRaspberryJuice#13]
G'day Martin. Thanks for this book and CanaryRaspberryJuice. I'm running through the book using CanaryRaspberryJuice and Minecraft 1.8 (CanaryMod) on Linux to familiarise myself with the workflow and results before handing it over to three eager kids.

Everything has been working great until I hit Adventure 4 and blockHit.py. As best as I've been able to determine, no matter which sword I use, I am not being returned event data. 

My code is here:
https://git.mcwhirter.io/craige/MyAdventures/blob/master/blockHit.py

I've also run your version from "Code Files" and neither version are returning any block hit events.

At different points I have also tried adding print statements, to print the event position but nothing is ever printed.

The code all runs without error but unfortunately also without any event data.

Do you have any ideas on where I could be digging to resolve this one?

Thanks!

**Comment by martinohanlon** [comment]
Can you confirm your are RIGHT clicking while holding a sword. Left click isn't a hit.

**Comment by craigem** [comment]
Oh wow, subtle but important distinction. I'd never used right-click for sword actions before.

Very happy to say that was indeed the solution. 

Thanks!
