### ISSUE TITLE
[minecraft 1.8] setBlock() not working

### ISSUE THREAD

**Issue by allkhor** [martinohanlon/CanaryRaspberryJuice#6]
Hello Martin, thanx for your work! It's realy help me to study Python and Java!
Tested with CanaryMod-Bleeding #121(120, 119) (stable)  + CanaryRaspberryJuice 1.0.2 + minecraft 1.8
world.setBlock() - not working, no error in console.. 
Maybe it's happened because in minecraft 1.8: 
Block ID numbers (such as 1 for stone), are being replaced by ID names (such as minecraft:stone)

It's bug of CanaryRaspberryJuice or CanaryMod?

**Comment by martinohanlon** [comment]
I have tested raspberryjuice with the release version of canarymod 1.8 and as far I can tell everything is working. I will likely be making some changes to the plugin to allow 'properties' to be used but block data still works for both setting and getting, so it works as-is for the moment.
